# Generated by Django 4.2.14 on 2024-07-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareceiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveddata',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='receiveddata',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
